name: Build binary files for release

on:
  release:
    types:
      - 'created'
      - 'edited'

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
    - run: ./gradlew assembleRelease --stacktrace
    - run: ./gradlew bundleRelease --stacktrace
    - name: Upload APK Release
    uses: actions/upload-artifact@v3
    with:
        path: ${{ env.main_project_module }}/build/outputs/apk/release/
    - name: Upload AAB (App Bundle) Release
    uses: actions/upload-artifact@v3
    with:
        path: ${{ env.main_project_module }}/build/outputs/bundle/release/
